name: hello workflow

on:
 push:
   branches: [main]

jobs:
  greet:
   runs-on: ubuntu-latest

   steps:
    - name: code checkout
      uses: actions/checkout@v4

    - name: say hello
      run: echo " hello from github actions!"

    - name: print current date and time
      run: date

    - name: print branch
      run: echo "on branch main"
      
    - name: list the files in repo
      run: ls -la

    - name: show OS
      run: echo "runner os:linux"

    - name: break the pipeline
      run: exit 1
      
   
